# Generated by Django 5.1.7 on 2025-03-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.TextField(blank=True)),
                ('course_title', models.CharField(max_length=100)),
                ('instructor', models.TextField(blank=True)),
            ],
        ),
    ]
